### ISSUE TITLE
submodules

### ISSUE THREAD

**Issue by IOExceptionOsu** [osuripple/cheesegull#11]
this is pretty simple but shouldn't [this stuff](https://github.com/osuripple/cheesegull/tree/master/vendor/github.com) use submodules?

any reason it wasn't done that way?

**Comment by thehowl** [comment]
`go get`. There are tools for dependency management in Go which use submodules, but when you run go get for the packages that use them, it doesn't work straight out of the box because go get does not automatically fetch submodules.

Another idea that is done in some other Go projects is that to have the Gopkg files but ignore the vendor folder, and have everyone run dep ensure in the project. However, this yet again impedes using go get and making it work straight out of the box. When dep is supported officially and implemented in the go toolchain, I will consider removing vendor and just making dep and Gopkg files do their magic.
